name: BuildAndDeploy
on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - client/**

permissions:
 id-token: write
 contents: read

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    env:
     AWS_DEFAULT_REGION: eu-west-2
    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js 16
      uses: actions/setup-node@v3
      with:
        node-version: 16 

    - name: Install Packages
      run: |
        cd client
        echo "REACT_APP_GOOGLE_API_KEY=${{ secrets.REACT_APP_GOOGLE_API_KEY }}" > .env
        echo "REACT_APP_HH_HEADER=${{ secrets.REACT_APP_HH_HEADER }}" >> .env
        npm install

    - name: Build React App
      run: |
        cd client
        CI=false npm run build
        echo "Build complete 🏗️"

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: ${{ vars.TF_AWS_ROLE }}
        role-session-name: samplerolesession
        aws-region: ${{env.AWS_DEFAULT_REGION}}

    - name: Sync S3 & Invalidate Caches
      run: |
        aws s3 sync client/build/ s3://${{ secrets.AWS_S3_BUCKET }}
        dist1=`aws cloudfront list-distributions --query "DistributionList.Items[?Comment=='hapihour.io'].Id" --output text`
        dist2=`aws cloudfront list-distributions --query "DistributionList.Items[?Comment=='www.hapihour.io'].Id" --output text`
        aws cloudfront create-invalidation --distribution-id $dist1 --paths "/*"
        aws cloudfront create-invalidation --distribution-id $dist2 --paths "/*"
